#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 27 20:41:07 2015

@author: appel
"""

if __name__ == '__main__':
    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('command', help='Command to execute', choices=['server',
                                                                       'list',
                                                                       'download',
                                                                       'upload',
                                                                       'add_server',
                                                                       'set_default_server',
                                                                       'search',
                                                                       'delete'])
    parser.add_argument('--index', '-i', type=str, default='1', help='Select the index')
    parser.add_argument('--workdir', '-w', type=str, default=None, help='Select the working directory')
    parser.add_argument('--overwrite', '-o', action='store_true', help='Overwrite worknote, if present')
    parser.add_argument('--server', '-s', type=str, default='', help='Set the server name')
    parser.add_argument('--url', type=str, default='', help='Set the server URL')
    parser.add_argument('--port', type=int, default=0, help='Set the server port')
    parser.add_argument('--chapter', '-c', type=str, default='', help='Chapter to upload worknote to')
    parser.add_argument('--query', '-q', type=str, default='', help='String to search for')
    parser.add_argument('--user', type=str, default='', help='Set the username')
    parser.add_argument('--pass', type=str, default='', help='Set the password')
    args = parser.parse_args()
    if args.command == 'server':
        import cherrypy
        from worknoteBookServer import worknoteBookServer
        cherrypy.quickstart(worknoteBookServer())
    else:
        from worknoteBookClient import worknoteBookClient
        client = worknoteBookClient()
        server_name = args.server
        if server_name == '':
            server_name = None
        if args.command == 'list':
            client.list()
        elif args.command == 'download':
            client.download(args.index, args.workdir, server_name)
        elif args.command == 'upload':
            client.upload(args.workdir, args.overwrite, server_name, args.chapter)
        elif args.command == 'add_server':
            client.add_server(server_name, args.url, args.port, args.user, args.pass)
        elif args.command == 'set_default_server':
            client.set_default_server(server_name)
        elif args.command == 'search':
            client.search(args.query, server_name)
        elif args.command == 'delete':
            client.delete(args.index, server_name)

