#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 27 20:41:07 2015

@author: appel
"""

if __name__ == '__main__':
    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('command', help='Command to execute', choices=['server',
                                                                       'list',
                                                                       'download',
                                                                       'upload'])
    parser.add_argument('--index', '-i', type=int, default=1, help='Select the index')
    parser.add_argument('--workdir', '-w', type=str, default=None, help='Select the working directory')
    parser.add_argument('--overwrite', '-o', action='store_true', help='Select the working directory')
    args = parser.parse_args()
    if args.command == 'server':
        from os.path import abspath
        import cherrypy
        from worknoteBookServer import worknoteBookServer
        conf = {
            '/': {
                'tools.staticdir.on': True,
                'tools.staticdir.root': abspath('../worknote/testbench'),
                'tools.staticdir.dir': '.'
            }
        }
        cherrypy.config.update({'server.socket_host': '0.0.0.0',
                                'server.socket_port': 8080})
        cherrypy.quickstart(worknoteBookServer('../worknote/testbench'), '/', conf)
    elif args.command == 'list':
        from worknoteBookClient import worknoteBookClient
        client = worknoteBookClient('localhost', 8080)
        client.list()
    elif args.command == 'download':
        from worknoteBookClient import worknoteBookClient
        client = worknoteBookClient('localhost', 8080)
        client.download(args.index, args.workdir)
    elif args.command == 'upload':
        from worknoteBookClient import worknoteBookClient
        client = worknoteBookClient('localhost', 8080)
        client.upload(args.workdir, args.overwrite)
